// <auto-generated />
namespace Quiron.LojaVirtual.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteração_bdoProduto_para_dboProdutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteração_bdoProduto_para_dboProdutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201605260146200_Alteração_bdo.Produto_para_dbo.Produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
